name: dmarsians-taekwondo
region: nyc
services:
- name: web
  source_dir: /
  github:
    repo: Helman143/Dmarsian
    branch: main
    deploy_on_push: true
  build_command: composer install --no-dev --optimize-autoloader
  run_command: php -S 0.0.0.0:8080 -t public public/index.php
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: APP_ENV
    value: production
    scope: RUN_TIME
  - key: DB_HOST
    value: ${db.HOSTNAME}
    scope: RUN_TIME
  - key: DB_USER
    value: ${db.USERNAME}
    scope: RUN_TIME
  - key: DB_PASS
    value: ${db.PASSWORD}
    scope: RUN_TIME
  - key: DB_NAME
    value: ${db.DATABASE}
    scope: RUN_TIME
  - key: DB_PORT
    value: ${db.PORT}
    scope: RUN_TIME

databases:
- name: db
  engine: MYSQL
  version: "8"
  production: false